<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>DailyWallpaper</AssemblyName>
    <Version>1.0.0</Version>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup><ProjectReference Include="../DailyWallpaper.Core/DailyWallpaper.Core.csproj" /></ItemGroup>
</Project>
